// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	model "github.com/aliskhannn/order-service/internal/model"
)

// MockorderRepository is a mock of orderRepository interface.
type MockorderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockorderRepositoryMockRecorder
}

// MockorderRepositoryMockRecorder is the mock recorder for MockorderRepository.
type MockorderRepositoryMockRecorder struct {
	mock *MockorderRepository
}

// NewMockorderRepository creates a new mock instance.
func NewMockorderRepository(ctrl *gomock.Controller) *MockorderRepository {
	mock := &MockorderRepository{ctrl: ctrl}
	mock.recorder = &MockorderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderRepository) EXPECT() *MockorderRepositoryMockRecorder {
	return m.recorder
}

// GetOrderById mocks base method.
func (m *MockorderRepository) GetOrderById(ctx context.Context, orderID string) (*model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderById", ctx, orderID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderById indicates an expected call of GetOrderById.
func (mr *MockorderRepositoryMockRecorder) GetOrderById(ctx, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderById", reflect.TypeOf((*MockorderRepository)(nil).GetOrderById), ctx, orderID)
}

// SaveOrder mocks base method.
func (m *MockorderRepository) SaveOrder(ctx context.Context, order *model.Order) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOrder", ctx, order)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveOrder indicates an expected call of SaveOrder.
func (mr *MockorderRepositoryMockRecorder) SaveOrder(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOrder", reflect.TypeOf((*MockorderRepository)(nil).SaveOrder), ctx, order)
}

// MockorderCache is a mock of orderCache interface.
type MockorderCache struct {
	ctrl     *gomock.Controller
	recorder *MockorderCacheMockRecorder
}

// MockorderCacheMockRecorder is the mock recorder for MockorderCache.
type MockorderCacheMockRecorder struct {
	mock *MockorderCache
}

// NewMockorderCache creates a new mock instance.
func NewMockorderCache(ctrl *gomock.Controller) *MockorderCache {
	mock := &MockorderCache{ctrl: ctrl}
	mock.recorder = &MockorderCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderCache) EXPECT() *MockorderCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockorderCache) Get(orderID string) (*model.Order, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", orderID)
	ret0, _ := ret[0].(*model.Order)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockorderCacheMockRecorder) Get(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockorderCache)(nil).Get), orderID)
}

// Set mocks base method.
func (m *MockorderCache) Set(orderID string, order *model.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", orderID, order)
}

// Set indicates an expected call of Set.
func (mr *MockorderCacheMockRecorder) Set(orderID, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockorderCache)(nil).Set), orderID, order)
}
