env: "development"

server:
  httpPort: ":8080"

database:
  sslmode: "disable"

kafka:
  groupID: "order-consumer-group-id"
  topic: "order.created"
  brokers:
    - "kafka:9092"
    - "kafka2:9093"
    - "kafka3:9094"

cache:
  defaultExpiration: "5m"
  cleanupInterval: "10m"
  preloadLimit: 100